layout_spectrum: 0.6682755737565458
typography_spectrum: 0.02736178319901228
color:
  brandStrength: 0.46679538604803383
  lightness: 0.0800730767659843
  saturation: 0.6619056051131338
  rhythmicContrast: 0.0024355670902878046
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
name: bruceallenphotograph.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/301c55f6-66e5-4161-a5cc-7b6422a600a3.png
